# Generated by Django 5.0.3 on 2024-04-03 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_app', '0002_students_attendence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendence',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
