# Generated by Django 5.0.3 on 2024-04-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_app', '0005_subjects_rename_semister_students_current_semister_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='subjects',
            field=models.ManyToManyField(to='attendence_app.subjects'),
        ),
    ]
