# Generated by Django 5.0.3 on 2024-04-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_app', '0006_attendence_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='subjects',
        ),
    ]
