# Generated by Django 5.0.3 on 2024-04-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_app', '0007_remove_attendence_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Attendence',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
