# Generated by Django 5.0.3 on 2024-04-03 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_app', '0008_remove_students_subjects_delete_attendence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('subject', models.CharField(max_length=50)),
                ('subject_faculty', models.CharField(max_length=25)),
                ('subject_semister', models.CharField(default='2', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('present_days', models.IntegerField()),
                ('absent_days', models.IntegerField()),
                ('is_present', models.BooleanField(default=False)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='attendence_app.students')),
                ('subjects', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendence_app.subjects')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
