# Generated by Django 5.0.3 on 2024-04-03 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_app', '0009_subjects_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence_app.subjects'),
        ),
    ]
