# Generated by Django 5.0.3 on 2024-04-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_app', '0012_students_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='absent_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='present_days',
            field=models.IntegerField(default=0),
        ),
    ]
