# Generated by Django 5.0.3 on 2024-04-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_app', '0013_alter_attendence_absent_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='is_present',
            field=models.BooleanField(),
        ),
    ]
