# Generated by Django 5.0.3 on 2024-04-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_app', '0014_alter_attendence_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='first_name',
            field=models.CharField(default='world', max_length=30),
        ),
        migrations.AddField(
            model_name='students',
            name='last_name',
            field=models.CharField(default='hello', max_length=30),
        ),
    ]
