# Generated by Django 5.0.3 on 2024-04-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_app', '0015_students_first_name_students_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='absent_days',
            new_name='total_days',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='is_present',
        ),
    ]
